/* 
 * Hanafuda game base class
 *
 */

#ifndef _HANAFUDA_H
#define _HANAFUDA_H

#include <stack>

typedef unsigned int CARD_ID;

typedef enum _HANAFUDA_CARD_SUIT {
    HANAFUDA_CARD_SUIT__FIRST = 0,
    HANAFUDA_CARD_SUIT__MATSU = HANAFUDA_CARD_SUIT__FIRST,
    HANAFUDA_CARD_SUIT__UME,
    HANAFUDA_CARD_SUIT__SAKURA,
    HANAFUDA_CARD_SUIT__FUJI,
    HANAFUDA_CARD_SUIT__AYAME,
    HANAFUDA_CARD_SUIT__BOTAN,
    HANAFUDA_CARD_SUIT__HAGI,
    HANAFUDA_CARD_SUIT__SUSUKI,
    HANAFUDA_CARD_SUIT__KIKU,
    HANAFUDA_CARD_SUIT__MOMIJI,
    HANAFUDA_CARD_SUIT__YANAGI,
    HANAFUDA_CARD_SUIT__KIRI,
    HANAFUDA_CARD_SUIT__MAX
} HANAFUDA_CARD_SUIT;

typedef enum _HANAFUDA_CARD_TYPE {
    HANAFUDA_CARD_TYPE__FIRST = 0,
    HANAFUDA_CARD_TYPE__NORMAL = HANAFUDA_CARD_TYPE__FIRST,
    HANAFUDA_CARD_TYPE__RIBBON_START,
    HANAFUDA_CARD_TYPE__RED_RIBBON = HANAFUDA_CARD_TYPE__RIBBON_START,
    HANAFUDA_CARD_TYPE__PURPLE_RIBBON,
    HANAFUDA_CARD_TYPE__POEM_RIBBON,
    HANAFUDA_CARD_TYPE__RIBBON_END = HANAFUDA_CARD_TYPE__POEM_RIBBON,
    HANAFUDA_CARD_TYPE__SPECIAL_START,
    HANAFUDA_CARD_TYPE__SPECIAL_CRANE = HANAFUDA_CARD_TYPE__SPECIAL_START,
    HANAFUDA_CARD_TYPE__SPECIAL_WARBLER,
    HANAFUDA_CARD_TYPE__SPECIAL_CURTAIN,
    HANAFUDA_CARD_TYPE__SPECIAL_CUCKOO,
    HANAFUDA_CARD_TYPE__SPECIAL_IRIS,
    HANAFUDA_CARD_TYPE__SPECIAL_BUTTERFLIES,
    HANAFUDA_CARD_TYPE__SPECIAL_BOAR,
    HANAFUDA_CARD_TYPE__SPECIAL_GEESE,
    HANAFUDA_CARD_TYPE__SPECIAL_MOON,
    HANAFUDA_CARD_TYPE__SPECIAL_SAKE,
    HANAFUDA_CARD_TYPE__SPECIAL_DEER,
    HANAFUDA_CARD_TYPE__SPECIAL_LIGHTNING,
    HANAFUDA_CARD_TYPE__SPECIAL_SWALLOW,
    HANAFUDA_CARD_TYPE__SPECIAL_RAINMAN,
    HANAFUDA_CARD_TYPE__SPECIAL_PHOENIX,
    HANAFUDA_CARD_TYPE__SPECIAL_END = HANAFUDA_CARD_TYPE__SPECIAL_PHOENIX,
    HANAFUDA_CARD_TYPE__MAX
} HANAFUDA_CARD_TYPE;

typedef struct _HANAFUDA_CARD {
    HANAFUDA_CARD_SUIT  suit;
    HANAFUDA_CARD_TYPE  type;
    unsigned int        value;
} HANAFUDA_CARD;

typedef enum { 
    HANAFUDA_NUM_CARDS      = 48,
    HANAFUDA_DECK_SIZE      = HANAFUDA_NUM_CARDS,
    HANAFUDA_CARDS_PER_SUIT = 4
};

class Hanafuda {
private:
    HANAFUDA_CARD          m_CardData[HANAFUDA_NUM_CARDS];
    std::stack<CARD_ID>    m_Deck;                         // being lazy and using C++ container

public:
    Hanafuda(void);
    virtual ~Hanafuda(void);

    HANAFUDA_CARD*  GetCard(CARD_ID id);

    void            Shuffle(void);
    bool            DrawCardFromTop(HANAFUDA_CARD *pOut);
    void            ClearDeck(void);

    virtual int     ScoreSet(CARD_ID *pHand, unsigned int handSize);

private:
    void SetupCards(void);
    void SetupDeck(void);
};

#endif